export enum CONSULTATION_FORMAT {
  FORMAT_EXPRESS = 1,
  FORMAT_FULL_CHAT = 2,
  FORMAT_FULL_VIDEO = 3
}

export enum CONSULTATION_FORMAT_PRICE {
  FORMT_EXPRESS_PRICE = 250,
  FORMT_FULL_PRICE = 2490,
}

export enum CONSULTATION_USER_ROLE {
  ROLE_CLIENT = 'client',
  ROLE_PSYCHOLOGIST = 'psychologist'
}

export enum CONSULTATION_FORM_ROUTE {
  FORMAT_EXPRESS = 'express',
  FORMAT_FULL = 'full'
}